apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: acharlas/ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftp
        - containerPort: 20
          name: ftp-data
        - containerPort: 4242
          name: ftp-pasv
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'pgrep telegraf && pgrep vsftpd'
          initialDelaySeconds: 5
          periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: acharlas
spec:
  selector:
    app: ftps
  ports:
    - protocol: TCP
      name: ftp
      port: 21
      targetPort: 21
      nodePort: 21
    - protocol: TCP
      name: ftp-data
      port: 20
      targetPort: 20
      nodePort: 20
    - protocol: TCP
      name: ftp-pasv
      port: 4242
      targetPort: 4242
      nodePort: 4242
  type: LoadBalancer
